# TODO: Add Drupal tools and excludes
# https://github.com/thinktandem/template-drupal8/blob/master/.lando.base.yml
# TODO: Replace events scripts with Lando-Extra ones, and with Apache/Nginx detector
keys: false
tooling:
  redis-cli:
    service: :service
    cmd: redis-cli
    user: www-data
    options:
      service:
        default: redis
        describe: Run php in different service
        alias:
          - s
  mysql:
    service: :service
    cmd: mysql
    user: root
    options:
      service:
        default: database
        describe: Run mysql in different service
        alias:
          - s
  php:
    service: :service
    cmd: php
    user: www-data
    options:
      service:
        default: appserver
        describe: Run php in different service
        alias:
          - s
  pickle:
    description: PHP extensions manager.
    service: :service
    cmd: pickle
    user: root
    options:
      service:
        default: appserver
        describe: Run pickle in different service
        alias:
          - s
  phpunitdebug:
    service: :service
    cmd: php -d xdebug.remote_port=9003 vendor/bin/phpunit
    user: www-data
    options:
      service:
        default: appserver
        describe: Run phpunit in different service
        alias:
          - s
  composer:
    service: :service
    cmd: composer
    user: www-data
    options:
      service:
        default: appserver
        describe: Run composer in different service
        alias:
          - s
  symfony:
    service: :service
    cmd: symfony
    options:
      service:
        default: appserver
        describe: Run symfony in different service
        alias:
          - s
  encore:
    service: :service
    cmd: encore
    options:
      service:
        default: node
        describe: Run encore in different service
        alias:
          - s
  artisan:
    service: :service
    cmd: artisan
    user: www-data
    options:
      service:
        default: appserver
        describe: Run artisan in different service
        alias:
          - s
  laravel:
    service: :service
    cmd: laravel
    user: www-data
    options:
      service:
        default: appserver
        describe: Run laravel in different service
        alias:
          - s
  pint:
    service: :service
    cmd: ./vendor/bin/pint
    user: www-data
    options:
      service:
        default: appserver
        describe: Run laravel in different service
        alias:
          - s
  wp:
    service: :service
    cmd: wp
    user: www-data
    options:
      service:
        default: appserver
        describe: Run wp in different service
        alias:
          - s
  n:
    service: :service
    cmd: cd ~ && bash n
    user: www-data
    options:
      service:
        default: appserver
        describe: Run n in different service
        alias:
          - s
  node:
    service: :service
    cmd: node
    options:
      service:
        default: node
        describe: Run node in different service
        alias:
          - s
  npx:
    service: :service
    cmd: npx
    options:
      service:
        default: node
        describe: Run npx in different service
        alias:
          - s
  npm:
    service: :service
    cmd: npm
    options:
      service:
        default: node
        describe: Run npm in different service
        alias:
          - s
  yarn:
    service: :service
    cmd: yarn
    options:
      service:
        default: node
        describe: Run yarn in different service
        alias:
          - s
  gulp:
    service: :service
    cmd: gulp
    options:
      service:
        default: node
        describe: Run it in a different service
        alias:
          - s
  next:
    service: :service
    cmd: next
    options:
      service:
        default: node
        describe: Run it in a different service
        alias:
          - s
  deno:
    service: :service
    cmd: /var/www/.deno/bin/deno
    options:
      service:
        default: appserver
        describe: Run it in a different service
        alias:
          - s
  python:
    service: :service
    cmd: python
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible:
    service: :service
    cmd: ansible
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-config:
    service: :service
    cmd: ansible-config
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-doc:
    service: :service
    cmd: ansible-doc
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-galaxy:
    service: :service
    cmd: ansible-galaxy
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-inventory:
    service: :service
    cmd: ansible-inventory
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-playbook:
    service: :service
    cmd: ansible-playbook
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-pull:
    service: :service
    cmd: ansible-pull
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  ansible-vault:
    service: :service
    cmd: ansible-vault
    options:
      service:
        default: python
        describe: Run it in a different service
        alias:
          - s
  xdebug-on:
    service: :service
    description: Enable xdebug.
    # APACHE
    #cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && /etc/init.d/apache2 reload && echo "Xdebug enabled"
    #NINGX
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Xdebug enabled"
    user: root
    options:
      service:
        default: appserver
        describe: Run it in a different service
        alias:
          - s
  xdebug-off:
    service: :service
    description: Disable xdebug.
    # APACHE
    #cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload && echo "Xdebug disabled"
    # NGINX
    cmd: rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Xdebug disabled"
    user: root
    options:
      service:
        default: appserver
        describe: Run it in a different service
        alias:
          - s
  'db-export [file]':
    service: :host
    description: Exports database from a database service to a file
    cmd: /helpers/sql-export.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      stdout:
        description: Dump database to stdout
  'db-import <file>':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    user: root
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: true
  drop-multisite-db-tables:
    service: :service
    description: Drop multisite tables
    cmd:
      - mysql -u root --skip-column-names -e "SET FOREIGN_KEY_CHECKS = 0; DROP TABLE IF EXISTS wp6w_blogs, wp6w_blogmeta, wp6w_blogs_versions, wp6w_registration_log, wp6w_signups, wp6w_site, wp6w_sitemeta;" wordpress
    user: root
    options:
      service:
        default: database
        describe: Run it in a different service
        alias:
          - s
  wp-sync-db:
    service: :service
    description: Imports a dump file into a WordPress database and search-replaces source domain with local domain
    cmd:
#      - echo 'FROM LIVE TO LOCAL'
      - wp search-replace '/full/path/to/app/on/server' '/app' --skip-columns=guid
      - wp search-replace '//www.example.com' '//example.lndo.site' --skip-columns=guid
      - wp search-replace 'www.example.com' 'example.lndo.site' --skip-columns=guid
      - wp search-replace '//example.com' '//example.lndo.site' --skip-columns=guid
      - wp search-replace 'example.com' 'example.lndo.site' --skip-columns=guid --skip-tables=wp_users
    user: www-data
    options:
      service:
        default: appserver
        describe: Run it in a different service
        alias:
          - s
excludes:
  - .git
  - .idea
  - vendor
  - node_modules
  - drush
  - scripts
  - web/core
  - web/modules/contrib
  - web/profiles/contrib
  - web/sites/default/files
  - web/themes/contrib