# Global parameter defaults
path: /app
debug: false
quiet: true
skip-plugins: true
skip-themes: true
skip-packages: true

# Subcommand defaults (e.g. `wp config create`)
config create:
  dbuser: wordpress
  dbpass: wordpress
  extra-php: |
    define( 'RECOVERY_MODE_EMAIL', 'foo@bar.com' );
    define( 'WP_DEBUG_DISPLAY', false );
    define( 'WP_DEBUG_LOG', '/app/php.log' );
    define( 'DISABLE_WP_CRON', true );
    define( 'AUTOSAVE_INTERVAL', 300 );
    define( 'WP_POST_REVISIONS', 5 );
    define( 'WP_CRON_LOCK_TIMEOUT', 120 );

# To enable .htaccess overwrite
apache_modules:
  - mod_rewrite
